import { useState } from 'react';
import { ArrowRight, Bot, CheckCheck, Download, FileSpreadsheet, Heart, PieChart, Plus, Rows3, ShieldCheck, Star, ThumbsUp, TrendingUp, UploadCloud } from 'lucide-react';
import '../styles/Home.css';

export default function Dashboard({ userName = 'User Name', dashboardStats, recentDatasets, isLoading, fileInputRef, onUpload, onNavigate }) {
  const [likedFeedback, setLikedFeedback] = useState({});
  const statCards = [[Rows3, 'Total Datasets', dashboardStats.totalDatasets], [CheckCheck, 'Cleaned Datasets', dashboardStats.cleanedDatasets]];
  const feedback = [
    { id: 1, name: 'Aarav Sharma', role: 'Data Analyst', text: 'The cleaning workflow saved me hours every week. The results are accurate and easy to review.', likes: 42 },
    { id: 2, name: 'Priya Mehta', role: 'Operations Manager', text: 'I love how quickly Cleanytics turns messy files into clear, usable datasets.', likes: 28 },
  ];
  const toggleLike = (id) => setLikedFeedback(current => ({ ...current, [id]: !current[id] }));

  return <div className="max-w-7xl mx-auto space-y-6 relative z-10">
    <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><h2 className="text-2xl font-bold">Welcome back, {userName} <span className="animate-wave inline-block">👋</span></h2><p className="text-sm text-[rgb(var(--text-s))] mt-1">Let AI clean your data and generate powerful insights.</p></div></div>
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4"><ActionCard icon={UploadCloud} title="Upload Data" text="Upload your CSV or Excel file to get started." action="Upload Now" onClick={() => fileInputRef.current?.click()}><input ref={fileInputRef} type="file" className="hidden" accept=".csv,.xlsx,.xls" onChange={onUpload} /></ActionCard><ActionCard icon={PieChart} title="Executive Dashboard" text="Get an executive summary with key insights." action="View Dashboard" onClick={() => onNavigate('Dashboard')} /><ActionCard icon={Download} title="Download Clean CSV" text="Download the cleaned and processed dataset." action="Download Now" onClick={() => onNavigate('History')} /><div className="bg-[rgba(var(--bg-surface),0.9)] border border-[rgba(var(--c-sec-rgb),0.4)] rounded-2xl p-5"><p className="text-xs text-[rgb(var(--text-s))]">DATA QUALITY SCORE</p><strong className="text-4xl block mt-3 text-[var(--c-main)]">{isLoading ? '—' : `${dashboardStats.qualityScore}%`}</strong><p className="text-xs text-[rgb(var(--text-s))] mt-2">Across your cleaned datasets</p></div></div>
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">{statCards.map(([Icon, label, value]) => <div key={label} className="jelly-hover p-5 rounded-2xl bg-[rgba(var(--bg-surface),0.9)] border border-[rgb(var(--border))]"><div className="flex items-center gap-2 text-[var(--c-main)]"><Icon size={18} /><p className="text-xs text-[rgb(var(--text-s))]">{label}</p></div><strong className="text-2xl block mt-2">{isLoading ? '—' : value}</strong></div>)}<div className="jelly-hover p-5 rounded-2xl bg-[rgba(var(--bg-surface),0.9)] border border-[rgb(var(--border))]"><p className="text-xs text-[rgb(var(--text-s))]">CLEANING IMPACT</p><div className="grid grid-cols-2 gap-x-4 gap-y-2 mt-3 text-xs"><span className="text-[rgb(var(--text-s))]">Rows before <strong className="block text-base text-[rgb(var(--text-p))]">{isLoading ? '—' : dashboardStats.originalRows.toLocaleString()}</strong></span><span className="text-[rgb(var(--text-s))]">Rows after <strong className="block text-base text-[var(--c-main)]">{isLoading ? '—' : dashboardStats.cleanedRows.toLocaleString()}</strong></span><span className="text-[rgb(var(--text-s))]">Columns before <strong className="block text-base text-[rgb(var(--text-p))]">{isLoading ? '—' : dashboardStats.originalColumns}</strong></span><span className="text-[rgb(var(--text-s))]">Columns after <strong className="block text-base text-[var(--c-main)]">{isLoading ? '—' : dashboardStats.cleanedColumns}</strong></span></div></div></div>
    <section className="recommendation-panel p-5 rounded-2xl border border-[rgba(var(--c-main-rgb),0.25)] bg-[linear-gradient(120deg,rgba(var(--c-main-rgb),.1),rgba(var(--c-sec-rgb),.04))]"><div className="flex items-start gap-3 mb-4"><div className="recommendation-icon"><Bot size={20} /></div><div><h3 className="font-semibold">Smart recommendations</h3><p className="text-xs text-[rgb(var(--text-s))] mt-1">Based on your workspace activity, here are your next best actions.</p></div></div><div className="grid grid-cols-1 md:grid-cols-3 gap-3"><Recommendation icon={UploadCloud} title="Clean a new file" text="Upload CSV or Excel data for automatic cleaning." action="Upload file" onClick={() => fileInputRef.current?.click()} /><Recommendation icon={TrendingUp} title="Improve data quality" text="Review recent results and find files needing attention." action="Review history" onClick={() => onNavigate('History')} /><Recommendation icon={ShieldCheck} title="Protect your workspace" text="Check your settings and keep your workspace secure." action="Open settings" onClick={() => onNavigate('Settings')} /></div></section>
    <section className="feedback-panel p-5 rounded-2xl border border-[rgba(var(--c-main-rgb),0.25)] bg-[rgba(var(--bg-surface),0.88)]"><div className="flex items-start gap-3 mb-4"><div className="feedback-heading-icon"><Heart size={19} /></div><div><h3 className="font-semibold">Top feedback</h3><p className="text-xs text-[rgb(var(--text-s))] mt-1">What users are saying about their cleaning workflow.</p></div></div><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{feedback.map(item => <article key={item.id} className="feedback-card"><div className="flex items-center justify-between gap-3"><div><strong className="text-sm">{item.name}</strong><span className="block text-[10px] text-[rgb(var(--text-s))] mt-0.5">{item.role}</span></div><div className="feedback-stars" aria-label="5 out of 5 stars">{[1, 2, 3, 4, 5].map(star => <Star key={star} size={13} fill="currentColor" />)}</div></div><p className="text-xs text-[rgb(var(--text-s))] leading-relaxed mt-3">“{item.text}”</p><button type="button" onClick={() => toggleLike(item.id)} className={`feedback-like ${likedFeedback[item.id] ? 'is-liked' : ''}`}><ThumbsUp size={13} fill={likedFeedback[item.id] ? 'currentColor' : 'none'} /> {item.likes + (likedFeedback[item.id] ? 1 : 0)} likes</button></article>)}</div></section>
    <section className="p-5 rounded-2xl bg-[rgba(var(--bg-surface),0.9)] border border-[rgb(var(--border))]"><div className="flex justify-between items-center mb-4"><div><h3 className="font-semibold">Recent datasets</h3><p className="text-xs text-[rgb(var(--text-s))] mt-1">Your latest uploaded files.</p></div><button onClick={() => onNavigate('History')} className="text-xs text-[var(--c-main)]">View all</button></div>{recentDatasets.length ? recentDatasets.map(file => <div key={file.id} className="flex items-center gap-3 py-3 border-t border-[rgb(var(--border))]"><FileSpreadsheet className="text-[var(--c-main)]" size={18} /><span className="text-sm flex-1">{file.name}</span><small className="text-xs text-[rgb(var(--text-s))]">{file.status}</small></div>) : <p className="text-sm text-[rgb(var(--text-s))]">No datasets yet. Upload your first file.</p>}</section>
  </div>;
}

function Recommendation({ icon: Icon, title, text, action, onClick }) { return <article className="recommendation-card jelly-hover"><div className="recommendation-card-icon"><Icon size={18} /></div><h4>{title}</h4><p>{text}</p><button onClick={onClick}>{action}<ArrowRight size={14} /></button></article>; }
function ActionCard({ icon: Icon, title, text, action, onClick, children }) { return <div onClick={onClick} className="jelly-hover bg-[rgba(var(--bg-surface),0.9)] border border-[rgb(var(--border))] rounded-2xl p-5 cursor-pointer hover:border-[rgba(var(--c-sec-rgb),0.5)] transition-all"><div className="flex items-start gap-4"><div className="p-3 bg-[rgba(var(--c-sec-rgb),0.1)] text-[var(--c-sec)] rounded-xl"><Icon className="w-6 h-6" /></div><div><h3 className="font-semibold">{title}</h3><p className="text-xs text-[rgb(var(--text-s))] mt-1 leading-relaxed">{text}</p></div></div>{children}<button className="jelly-button w-full mt-5 py-2 bg-[rgba(var(--bg-hover),0.6)] border border-[rgb(var(--border))] rounded-lg text-[var(--c-sec)] text-xs">{action} <Plus className="inline w-3.5 h-3.5" /></button></div>; }

